// it's not mandatory to have separate success/fail types

export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAIL = 'GET_ARTICLE_FAIL';

export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_FAIL = 'ADD_ARTICLE_FAIL';


export const RECEIVE_ARTICLES = 'GET_ARTICLES';
export const RECEIVE_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const RECEIVE_ARTICLES_FAIL = 'GET_ARTICLES_FAIL';


export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL';

export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL';


export const REPLACE_ARTICLE = 'REPLACE_ARTICLE';
export const REPLACE_ARTICLE_SUCCESS = 'REPLACE_ARTICLE_SUCCESS';
export const REPLACE_ARTICLE_FAIL = 'REPLACE_ARTICLE_FAIL';